apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment-{{ .Values.environment }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}-deployment-{{ .Values.environment }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-deployment-{{ .Values.environment }}"
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/service: {{ .Values.name }}
        tags.datadoghq.com/version: {{ .Values.version }}
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: v5.67.0
    spec:
      containers:
      - name: "{{ .Values.name }}-deployment-{{ .Values.environment }}"
        image: "{{ .Values.image }}:{{ .Values.version }}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "4000"
          - name: APP_KEY
            value: QiP8eyyVqSGfeDkRsgUGeKDINRlB5MMC
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: postgres
          - name: DB_DATABASE
            value: postgres
          - name: HOST
            value: "0.0.0.0"
          - name: LOG_LEVEL
            value: error
          - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
          - name: DD_APPSEC_SCA_ENABLED
            value: "true"
          - name: DD_GIT_COMMIT_SHA
            value: "{{ .Values.version }}"  
          - name: DD_GIT_REPOSITORY_URL
            value: "github.com/devops-estudos/micro-services"
        ports:
        - name: http
          containerPort: 4000
        