apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-deployment
  template:
    metadata:
      labels:
        app: contacts-deployment
    spec:
      containers:
      - name: contacts-deployment
        image: 203918840319.dkr.ecr.us-east-1.amazonaws.com/contacts:279a37a
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "4000"
          - name: APP_KEY
            value: QiP8eyyVqSGfeDkRsgUGeKDINRlB5MMC
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: postgres
          - name: DB_DATABASE
            value: postgres
          - name: HOST
            value: localhost
          - name: LOG_LEVEL
            value: error
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - name: http
          protocol: TCP
          containerPort: 4000