apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: production-eks
    registry: public.ecr.aws/datadog
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  override:
    nodeAgent:
      env:
      - name: DD_CONTAINER_INCLUDE
        value: "kube_namespace:production kube_namespace:staging"
  features:
    apm:
      enabled: true
    npm:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: true
