apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: production-eks
    registry: public.ecr.aws/datadog
    site: datadoghq.com
    credentials:
      apiKey: b7eabfc84ed9051875592b3f07537fbb
      appKey: 944fabcc28e0a6cf5aa797725cd1754c010fe8d5
      
  features:
    apm:
      enabled: true
    npm:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true